### ISSUE TITLE
sorting by columns on vault dashboard

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/onebtc.frontend#16]
can you add sorting based on these columns? 

<img width="1887" alt="Screen Shot 2022-01-31 at 10 35 12 AM" src="https://user-images.githubusercontent.com/13854340/151852507-fe12d0eb-0027-4219-a524-dd037805b072.png">

similarly if there are any other dashboards, if they can be sorted, please add the feature on all of those.

**Comment by ahiipsa** [comment]
done, waiting this pr: https://github.com/harmony-one/onebtc.relayer-client/pull/57

**Comment by potvik** [comment]
Done
