### ISSUE TITLE
BTC Bridge UI issues

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/onebtc.frontend#18]
1. Collateralization ratio seems wrong (too large)
<img width="1730" alt="Screen Shot 2022-02-08 at 7 23 18 PM" src="https://user-images.githubusercontent.com/13854340/153116062-254f4a91-c8ec-4640-8eff-12027ce29abc.png">

2. Redeem fee is not consistent with Issue fee
<img width="588" alt="Screen Shot 2022-02-08 at 7 21 12 PM" src="https://user-images.githubusercontent.com/13854340/153116143-f01f6f15-ce5b-47ce-9172-de82b3301a8f.png">

3. "Add 1BTC to metamask" button needed
<img width="739" alt="Screen Shot 2022-02-08 at 5 44 42 PM" src="https://user-images.githubusercontent.com/13854340/153116170-5388363c-8631-41af-b88d-efd46979106a.png">

4. Change the message from "I don't like this vault, let me select another" to "Manually select vault"
 <img width="703" alt="Screen Shot 2022-02-08 at 4 46 20 PM" src="https://user-images.githubusercontent.com/13854340/153116322-7edfa184-d639-4a7f-920b-582c156d03cd.png">

5. Add a message somewhere, "Please only send the exact amount, as over payment will not return the excess BTC"
<img width="620" alt="Screen Shot 2022-02-08 at 4 36 04 PM" src="https://user-images.githubusercontent.com/13854340/153116459-095b7e2c-acdd-4968-8612-57ed23ffae43.png">

**Comment by potvik** [comment]
Fixed
