### ISSUE TITLE
some minor frontend issues

### ISSUE THREAD

**Issue by gupadhyaya** [harmony-one/onebtc.frontend#3]
1. if wallet is not connected before issue/redeem, warn the user with correct message than just error
<img width="1249" alt="Screen Shot 2021-11-01 at 11 39 21 AM" src="https://user-images.githubusercontent.com/13854340/139758052-6c670822-cc69-412e-af34-1c6a6c54fac9.png">

2. show full address, as there is enough space without cluttering
<img width="1633" alt="Screen Shot 2021-11-01 at 1 07 34 PM" src="https://user-images.githubusercontent.com/13854340/139758067-87a60df4-97f3-4f05-8177-cbb1de0dd58e.png">

**Comment by gupadhyaya** [comment]
some more @ahiipsa
<img width="1287" alt="Screen Shot 2021-11-01 at 9 23 16 PM" src="https://user-images.githubusercontent.com/13854340/139786706-a9602ef3-a8bd-45d3-a8c5-b6be32d971fd.png">

**Comment by gupadhyaya** [comment]
some more @ahiipsa 
<img width="1260" alt="Screen Shot 2021-11-01 at 9 26 30 PM" src="https://user-images.githubusercontent.com/13854340/139787016-8328f91a-b44b-4f72-9de3-560e8a776a5c.png">
<img width="1245" alt="Screen Shot 2021-11-01 at 9 25 54 PM" src="https://user-images.githubusercontent.com/13854340/139787017-de8a9ef7-1d33-4d8b-b99f-a5b95ae6581a.png">
<img width="1204" alt="Screen Shot 2021-11-01 at 9 25 26 PM" src="https://user-images.githubusercontent.com/13854340/139787019-a4df2c2f-ea16-4065-8f6f-f77ec614715d.png">

**Comment by ahiipsa** [comment]
> show full address, as there is enough space without cluttering
@gupadhyaya 

it look good if screen resolution more than 1600px

for example at macbook 13" it looks like this:
![image](https://user-images.githubusercontent.com/1662798/139941146-b94f7d09-b203-4383-abb0-93c46c2cad51.png)


i can add tooltip:
![image](https://user-images.githubusercontent.com/1662798/139940804-e4c806ca-cebb-4dba-b204-e7b5d2aa7fba.png)

or change layout:

![image](https://user-images.githubusercontent.com/1662798/139941420-8db4acb7-035e-4b44-b440-bc7b01db10fc.png)
